# Instructions to execute pre-commit locally
# Help https://github.com/pre-commit/pre-commit-hooks

# Install pre-commit-hooks in your local machine and execute
#  $ pip install pre-commit-hooks
#  $ pre-commit run -a

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
